{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "java-backend1.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-backend1.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.azureKeyVault.enabled }}
    azure.workload.identity/client-id: {{ .Values.azureKeyVault.userAssignedIdentityID | quote }}
    azure.workload.identity/tenant-id: {{ .Values.azureKeyVault.tenantId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.azureKeyVault.enabled | default false }}
{{- end }}